#pragma once

#include <QApplication>
#include <QLabel>
#include <QFont>
#include <QComboBox>
#include <QGridLayout>
#include <QVBoxLayout>
#include <QPlainTextEdit>
#include <QAudioDevice>
#include <QMediaDevices>
#include <QObject>
#include <QMetaObject>
#include <QPushButton>
#include <QSpinBox>
#include <QDialog>
#include <QKeySequenceEdit>
#include <QKeySequence>
#include <QJsonDocument>
#include <QJsonObject>
#include <QDir>
#include <QFileInfo>
#include <QFile>
#include <QMessageBox>
#include <QCheckBox>
